---
openapi: 3.0.0
info:
  title: Currency/Rate API
  description: This is a simple currency management API
  contact:
    email: vzateychuk@gmail.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 2.0.0
servers:
- url: https://virtserver.swaggerhub.com/VZATEYCHUK/bank/2.0.0
  description: SwaggerHub API Auto Mocking
tags:
- name: currency
  description: Operations with currencies
paths:
  /currency:
    get:
      tags:
      - currency
      summary: searches currencies
      description: |
        By passing in the appropriate options, you can search for
        available currency in the system
      operationId: searchCurrency
      parameters:
      - name: code
        in: query
        description: pass currency-code for looking up currency
        required: true
        style: form
        explode: true
        schema:
          type: string
          example: RUB
      responses:
        "200":
          description: search results matching criteria
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CurrencyRate'
        "400":
          description: bad skip/limit values
        "404":
          description: currency code not found
    post:
      tags:
      - currency
      summary: add/update currency/rate
      description: Add currency/rate to the system
      operationId: addCurrency
      requestBody:
        description: Currency/Rate to add
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CurrencyRate'
      responses:
        "201":
          description: currency upserted
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CurrencyRate'
        "400":
          description: "invalid input, object invalid"
  /currency/{code}:
    get:
      tags:
      - currency
      summary: get currency details (rate asof date/time)
      description: |
        Get currency rate asof date/time
      operationId: getCurrencyRate
      parameters:
      - name: code
        in: path
        description: currency code
        required: true
        style: simple
        explode: false
        schema:
          type: string
          example: USD
      responses:
        "200":
          description: currency rate asof Now
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CurrencyRate'
        "400":
          description: input date/time incorrect
        "404":
          description: currency code not found
components:
  schemas:
    CurrencyRate:
      required:
      - code
      - rate
      type: object
      properties:
        code:
          type: string
          description: currency code
          example: RUB
        rate:
          type: number
          description: rate value agains base currency
          example: 91.8
        name:
          type: string
          description: currency name
          example: Russan Ruble
